// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: simpleMessage.proto
// Protobuf C++ Version: 6.32.1

#include "simpleMessage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace simple {

inline constexpr SimpleMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sender_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SimpleMessage::SimpleMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SimpleMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimpleMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimpleMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimpleMessageDefaultTypeInternal() {}
  union {
    SimpleMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimpleMessageDefaultTypeInternal _SimpleMessage_default_instance_;
}  // namespace simple
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_simpleMessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_simpleMessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_simpleMessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::simple::SimpleMessage, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::simple::SimpleMessage, _impl_.sender_name_),
        PROTOBUF_FIELD_OFFSET(::simple::SimpleMessage, _impl_.data_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::simple::SimpleMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::simple::_SimpleMessage_default_instance_._instance,
};
const char descriptor_table_protodef_simpleMessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023simpleMessage.proto\022\006simple\"2\n\rSimpleM"
    "essage\022\023\n\013sender_name\030\001 \001(\t\022\014\n\004data\030\002 \001("
    "\005b\006proto3"
};
static ::absl::once_flag descriptor_table_simpleMessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_simpleMessage_2eproto = {
    false,
    false,
    89,
    descriptor_table_protodef_simpleMessage_2eproto,
    "simpleMessage.proto",
    &descriptor_table_simpleMessage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_simpleMessage_2eproto::offsets,
    file_level_enum_descriptors_simpleMessage_2eproto,
    file_level_service_descriptors_simpleMessage_2eproto,
};
namespace simple {
// ===================================================================

class SimpleMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SimpleMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_._has_bits_);
};

SimpleMessage::SimpleMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SimpleMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:simple.SimpleMessage)
}
PROTOBUF_NDEBUG_INLINE SimpleMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::simple::SimpleMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sender_name_(arena, from.sender_name_) {}

SimpleMessage::SimpleMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SimpleMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SimpleMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimpleMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.data_ = from._impl_.data_;

  // @@protoc_insertion_point(copy_constructor:simple.SimpleMessage)
}
PROTOBUF_NDEBUG_INLINE SimpleMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sender_name_(arena) {}

inline void SimpleMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.data_ = {};
}
SimpleMessage::~SimpleMessage() {
  // @@protoc_insertion_point(destructor:simple.SimpleMessage)
  SharedDtor(*this);
}
inline void SimpleMessage::SharedDtor(MessageLite& self) {
  SimpleMessage& this_ = static_cast<SimpleMessage&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SimpleMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SimpleMessage(arena);
}
constexpr auto SimpleMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SimpleMessage),
                                            alignof(SimpleMessage));
}
constexpr auto SimpleMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SimpleMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SimpleMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SimpleMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SimpleMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SimpleMessage>(), &SimpleMessage::ByteSizeLong,
              &SimpleMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_._cached_size_),
          false,
      },
      &SimpleMessage::kDescriptorMethods,
      &descriptor_table_simpleMessage_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SimpleMessage_class_data_ =
        SimpleMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SimpleMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SimpleMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SimpleMessage_class_data_.tc_table);
  return SimpleMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2>
SimpleMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SimpleMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::simple::SimpleMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 data = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SimpleMessage, _impl_.data_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_.data_)}},
    // string sender_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_.sender_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender_name = 1;
    {PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_.sender_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 data = 2;
    {PROTOBUF_FIELD_OFFSET(SimpleMessage, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\24\13\0\0\0\0\0\0"
    "simple.SimpleMessage"
    "sender_name"
  }},
};
PROTOBUF_NOINLINE void SimpleMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:simple.SimpleMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.sender_name_.ClearNonDefaultToEmpty();
  }
  _impl_.data_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SimpleMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SimpleMessage& this_ = static_cast<const SimpleMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SimpleMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SimpleMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:simple.SimpleMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string sender_name = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_sender_name().empty()) {
      const ::std::string& _s = this_._internal_sender_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "simple.SimpleMessage.sender_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 data = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_data() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_data(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:simple.SimpleMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SimpleMessage::ByteSizeLong(const MessageLite& base) {
  const SimpleMessage& this_ = static_cast<const SimpleMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SimpleMessage::ByteSizeLong() const {
  const SimpleMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:simple.SimpleMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // string sender_name = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_sender_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_sender_name());
      }
    }
    // int32 data = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_data() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_data());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SimpleMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SimpleMessage*>(&to_msg);
  auto& from = static_cast<const SimpleMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:simple.SimpleMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_sender_name().empty()) {
        _this->_internal_set_sender_name(from._internal_sender_name());
      } else {
        if (_this->_impl_.sender_name_.IsDefault()) {
          _this->_internal_set_sender_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_data() != 0) {
        _this->_impl_.data_ = from._impl_.data_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleMessage::CopyFrom(const SimpleMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:simple.SimpleMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SimpleMessage::InternalSwap(SimpleMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_name_, &other->_impl_.sender_name_, arena);
  swap(_impl_.data_, other->_impl_.data_);
}

::google::protobuf::Metadata SimpleMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace simple
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_simpleMessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
